### ISSUE TITLE
Project Gutenberg's files are now patched

### ISSUE THREAD

**Issue by gbnewby** [NYPL/cce-renewals#1]
The six patch sets referenced in cce-renewals/data/pre-patches/*diff have now been applied to the Project Gutenberg sources.

Thank you for these errata reports. Further reports may be sent to the errata@ or help@ address here: https://www.gutenberg.org/wiki/Gutenberg:Contact_Information

**Comment by seanredmond** [comment]
That is great, thank you! I'll start sending things to the errata address
